### ISSUE TITLE
using with https elastic url

### ISSUE THREAD

**Issue by johnqa** [anasoid/jmeter-logstash#55]
Hi,

I am trying to use this image to send data from my jmeter execution to an https url of elastic search, but I am getting the requests rejected due to missing certificates.

Where can I put the needed certificates to enable ssl/tls communication?

Thank you

**Comment by anasoid** [comment]
hi @johnqa ,

can you give me more detail on your need ?

**Comment by johnqa** [comment]
Hi,

So for more details I am running this command: 
```
docker run --rm -e "ELASTICSEARCH_HOSTS=https://elastic_server:9200" \
-v results:/input/ \
-e "FILE_READ_MODE=read" \
-e "FILE_COMPLETED_ACTION=delete" \
-e "ELASTICSEARCH_INDEX=test-jmeter" \
-e "ELASTICSEARCH_USER=user" \
-e "ELASTICSEARCH_PASSWORD=password." \
anasoid/jmeter-logstash
```

and get this error:
```
[2023-10-09T08:50:13,890][INFO ][logstash.outputs.elasticsearch][main] Failed to perform request {:message=>"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target", :exception=>Manticore::ClientProtocolException, :cause=>javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}
[2023-10-09T08:50:13,891][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"https://elastic_server:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [https://elastic_server:9200/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}
```

And the question is how can I pass the certificate.

**Comment by anasoid** [comment]
what is the elastic server version? do you have a valid certificate on https ? to login to elastic server user/password is sufficient or  certificate is needed?

The config is working fine with https server with valid https certificate

**Comment by johnqa** [comment]
Well but where should the certificate be? The error is "unable to find valid certification path to requested target" but i do not give any certificate anywhere, in the command I am using.

**Comment by anasoid** [comment]
hello,
can you give me the elasticsearch version ?

**Comment by johnqa** [comment]
hi, we have Elastic Search v8.9

**Comment by anasoid** [comment]
hello @johnqa 

can you remove the anasoi/jmeter-logstash uimage and pull new version or just use this version (7.17.14) and use the folowing command ?

docker run --rm -e "ELASTICSEARCH_HOSTS=https://elastic_server:9200" \
-v results:/input/ \
-e "FILE_READ_MODE=read" \
-e "FILE_COMPLETED_ACTION=delete" \
-e "ELASTICSEARCH_INDEX=test-jmeter" \
-e "ELASTICSEARCH_USER=user" \
-e "ELASTICSEARCH_PASSWORD=password." \
-e "ELASTICSEARCH_SSL_VERIFICATION=false" \
-e ELASTICSEARCH_VERSION=8 \
anasoid/jmeter-logstash


only thoes param are add to your initial command 

-e "ELASTICSEARCH_SSL_VERIFICATION=false" \
-e ELASTICSEARCH_VERSION=8 \

**Comment by johnqa** [comment]
Hi, 
Thank you for the effort. 
I have did what you wrote and now I have these logs:

```
[2023-10-17T09:51:03,498][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties
[2023-10-17T09:51:03,508][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.17.14", "jruby.version"=>"jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 OpenJDK 64-Bit Server VM 11.0.20+8 on 11.0.20+8 +indy +jit [linux-x86_64]"}
[2023-10-17T09:51:03,509][INFO ][logstash.runner          ] JVM bootstrap flags: [-Xms256m, -Xmx512m, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djdk.io.File.enableADS=true, -Djruby.compile.invokedynamic=true, -Djruby.jit.threshold=0, -Djruby.regexp.interruptible=true, -XX:+HeapDumpOnOutOfMemoryError, -Djava.security.egd=file:/dev/urandom, -Dlog4j2.isThreadContextMapInheritable=true, -Dls.cgroup.cpuacct.path.override=/, -Dls.cgroup.cpu.path.override=/]
[2023-10-17T09:51:03,539][INFO ][logstash.settings        ] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
[2023-10-17T09:51:03,550][INFO ][logstash.settings        ] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
[2023-10-17T09:51:03,863][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"53141d19-138a-4dae-9398-afd448087651", :path=>"/usr/share/logstash/data/uuid"}
[2023-10-17T09:51:04,572][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}
[2023-10-17T09:51:06,425][INFO ][org.reflections.Reflections] Reflections took 87 ms to scan 1 urls, producing 119 keys and 419 values 
[2023-10-17T09:51:08,446][WARN ][org.logstash.instrument.metrics.gauge.LazyDelegatingGauge][jtl-csv] A gauge metric of an unknown type (org.jruby.specialized.RubyArrayOneObject) has been created for key: send_to. This may result in invalid serialization.  It is recommended to log an issue to the responsible developer/development team.
[2023-10-17T09:51:08,527][INFO ][logstash.javapipeline    ][jtl-csv] Starting pipeline {:pipeline_id=>"jtl-csv", "pipeline.workers"=>1, "pipeline.batch.size"=>1, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1, "pipeline.sources"=>["/usr/share/logstash/pipeline-in-csv/filter-wait-logstash.conf", "/usr/share/logstash/pipeline-in-csv/input-csv-logstash.conf", "/usr/share/logstash/pipeline-in-csv/output-next-pipeline-logstash.conf"], :thread=>"#<Thread:0x15e6e0a9 run>"}
[2023-10-17T09:51:09,968][INFO ][logstash.javapipeline    ][jtl-csv] Pipeline Java execution initialization time {"seconds"=>1.44}
[2023-10-17T09:51:10,173][INFO ][logstash.inputs.file     ][jtl-csv] No sincedb_path set, generating one based on the "path" setting {:sincedb_path=>"/usr/share/logstash/data/plugins/inputs/file/.sincedb_2e3001482a97bd583a361a059b521f94", :path=>["/input/**.jtl", "/input/**.jtl"]}
[2023-10-17T09:51:10,195][INFO ][logstash.javapipeline    ][jtl-csv] Pipeline started {"pipeline.id"=>"jtl-csv"}
[2023-10-17T09:51:10,242][INFO ][filewatch.observingread  ][jtl-csv][jtl-input] START, creating Discoverer, Watch with file and sincedb collections
[2023-10-17T09:51:10,620][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://elk-server:9200"]}
[2023-10-17T09:51:10,666][WARN ][logstash.outputs.elasticsearch][main] You have enabled encryption but DISABLED certificate verification, to make sure your data is secure remove `ssl_certificate_verification => false`
[2023-10-17T09:51:10,945][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://elk-user:***@elk-server:9200/]}}
[2023-10-17T09:51:11,298][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"https://elk-user:***@elk-server:9200/"}
[2023-10-17T09:51:11,313][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.17.0) {:es_version=>7}
[2023-10-17T09:51:11,315][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-10-17T09:51:11,408][INFO ][logstash.outputs.elasticsearch][main] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2023-10-17T09:51:11,409][INFO ][logstash.outputs.elasticsearch][main] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2023-10-17T09:51:11,410][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://elk-server:9200"]}
[2023-10-17T09:51:11,411][WARN ][logstash.outputs.elasticsearch][main] You have enabled encryption but DISABLED certificate verification, to make sure your data is secure remove `ssl_certificate_verification => false`
[2023-10-17T09:51:11,420][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://elk-user:***@elk-server:9200/]}}
[2023-10-17T09:51:11,455][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"https://elk-user:***@elk-server:9200/"}
[2023-10-17T09:51:11,456][INFO ][logstash.outputs.elasticsearch][main] Using mapping template from {:path=>"/usr/share/logstash/pipeline/template/jmeter-jtl-8x.json"}
[2023-10-17T09:51:11,463][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.17.0) {:es_version=>7}
[2023-10-17T09:51:11,463][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-10-17T09:51:11,472][INFO ][logstash.outputs.elasticsearch][main] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2023-10-17T09:51:11,472][INFO ][logstash.outputs.elasticsearch][main] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2023-10-17T09:51:11,484][INFO ][logstash.outputs.elasticsearch][main] Using mapping template from {:path=>"/usr/share/logstash/pipeline/template/jmeter-jtl-8x.json"}
[2023-10-17T09:51:11,490][INFO ][logstash.outputs.elasticsearch][main] Installing Elasticsearch template {:name=>"jmeter-jtl"}
[2023-10-17T09:51:11,563][ERROR][logstash.outputs.elasticsearch][main] Failed to install template {:message=>"Got response code '403' contacting Elasticsearch at URL 'https://elk-server:9200/_template/jmeter-jtl'", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:84:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:324:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:311:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_cl...
[2023-10-17T09:51:11,567][ERROR][logstash.outputs.elasticsearch][main] Failed to install template {:message=>"Got response code '403' contacting Elasticsearch at URL 'https://elk-server:9200/_template/jmeter-jtl'", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:84:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:324:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:311:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch/http_cl...
[2023-10-17T09:51:11,721][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/usr/share/logstash/pipeline/filter-a-config-fields-logstash.conf", "/usr/share/logstash/pipeline/filter-a-jtl-csv-filter-logstash.conf", "/usr/share/logstash/pipeline/filter-aa-jtl-fields-logstash.conf", "/usr/share/logstash/pipeline/filter-aa-jtl-filter-logstash.conf", "/usr/share/logstash/pipeline/filter-aa-jtl-transaction-logstash.conf", "/usr/share/logstash/pipeline/filter-aa-stats-adapt-json-logstash.conf", "/usr/share/logstash/pipeline/filter-bb-clean-null.conf", "/usr/share/logstash/pipeline/filter-bb-stats-parse-json-logstash.conf", "/usr/share/logstash/pipeline/filter-cc-stats-round-value-logstash.conf", "/usr/share/logstash/pipeline/filter-oo-jtl-thread-logstash.conf", "/usr/share/logstash/pipeline/filter-oo-jtl-time-logstash.conf", "/usr/share/logstash/pipeline/f...
[2023-10-17T09:51:13,746][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>2.02}
[2023-10-17T09:51:13,768][INFO ][logstash.inputs.file     ][main] No sincedb_path set, generating one based on the "path" setting {:sincedb_path=>"/usr/share/logstash/data/plugins/inputs/file/.sincedb_3bf673c089affb26c6b714f2f3224e92", :path=>["/input/**.json", "/input/**.json"]}
[2023-10-17T09:51:13,772][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-10-17T09:51:13,786][INFO ][filewatch.observingread  ][main][statistics-input] START, creating Discoverer, Watch with file and sincedb collections
[2023-10-17T09:51:13,812][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:"jtl-csv", :main], :non_running_pipelines=>[]}


[2023-10-17T09:51:14,108][WARN ][logstash.filters.json    ][main][794d1cb7acae434dfcf3c2d8ddd78a3fda55a594d763229e305a91f5871eac0d] Error parsing json {:source=>"message", :raw=>"  },   \"gui\": {    \"modules\": {     \"jmeter\": {      \"gui\": true     }    }", :exception=>#<LogStash::Json::ParserError: Unexpected close marker '}': expected ']' (for root starting at [Source: (byte[])"  },   "gui": {    "modules": {     "jmeter": {      "gui": true     }    }"; line: 1, column: 0])
 at [Source: (byte[])"  },   "gui": {    "modules": {     "jmeter": {      "gui": true     }    }"; line: 1, column: 4]>}
  

[2023-10-17T09:51:14,115][WARN ][logstash.filters.json    ][main][794d1cb7acae434dfcf3c2d8ddd78a3fda55a594d763229e305a91f5871eac0d] Error parsing json {:source=>"message", :raw=>" },  \"execution\": [   {    \"scenario\": \"${ScenarioName}\"   }  ],  \"scenarios\": {   \"elkintegration\": {    \"script\": \"/bzt-configs/TestApp4JMeterLoadTests/LoadTests/elkintegration.jmx\"   }", :exception=>#<LogStash::Json::ParserError: Unexpected close marker '}': expected ']' (for root starting at [Source: (byte[])" },  "execution": [   {    "scenario": "${ScenarioName}"   }  ],  "scenarios": {   "elkintegration": {    "script": "/bzt-configs/TestApp4JMeterLoadTests/LoadTests/elkintegration.jmx"   }"; line: 1, column: 0])
 at [Source: (byte[])" },  "execution": [   {    "scenario": "${ScenarioName}"   }  ],  "scenarios": {   "elkintegration": {    "script": "/bzt-configs/TestApp4JMeterLoadTests/LoadTests/elkintegration.jmx"   }"; line: 1, column: 3]>}

 
 [2023-10-17T09:51:14,396][WARN ][logstash.outputs.elasticsearch][main][jmeter-elasticsearch-output-stat] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"jmeter-jtl-2023.10.17", :routing=>nil}, {"isTotal"=>false, "labels"=>["%{transaction}"], "@version"=>"1", "globalLabel"=>"%{transaction}", "filename"=>"effective", "@timestamp"=>2023-10-17T09:51:13.835Z, "testname"=>"effective", "timestamp"=>"2023-10-17T09:51:13.835Z", "label"=>"%{transaction}", "tags"=>["_jsonparsefailure"], "project"=>"undefined", "origin"=>"stat"}], :response=>{"index"=>{"_index"=>"jmeter-jtl-2023.10.17", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"only write ops with an op_type of create are allowed in data streams"}}}}
[2023-10-17T09:51:14,400][WARN ][logstash.outputs.elasticsearch][main][jmeter-elasticsearch-output-stat] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"jmeter-jtl-2023.10.17", :routing=>nil}, {"isTotal"=>false, "labels"=>["%{transaction}"], "@version"=>"1", "globalLabel"=>"%{transaction}", "filename"=>"effective", "@timestamp"=>2023-10-17T09:51:13.826Z, "testname"=>"effective", "timestamp"=>"2023-10-17T09:51:13.826Z", "label"=>"%{transaction}", "tags"=>["_jsonparsefailure"], "project"=>"undefined", "origin"=>"stat"}], :response=>{"index"=>{"_index"=>"jmeter-jtl-2023.10.17", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"only write ops with an op_type of create are allowed in data streams"}}}}
[2023-10-17T09:51:14,397][WARN ][logstash.outputs.elasticsearch][main][jmeter-elasticsearch-output-stat] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"jmeter-jtl-2023.10.17", :routing=>nil}, {"isTotal"=>false, "labels"=>["%{transaction}"], "@version"=>"1", "globalLabel"=>"%{transaction}", "filename"=>"effective", "@timestamp"=>2023-10-17T09:51:13.863Z, "testname"=>"effective", "timestamp"=>"2023-10-17T09:51:13.863Z", "label"=>"%{transaction}", "tags"=>["_jsonparsefailure"], "project"=>"undefined", "origin"=>"stat"}], :response=>{"index"=>{"_index"=>"jmeter-jtl-2023.10.17", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"only write ops with an op_type of create are allowed in data streams"}}}}
[2023-10-17T09:51:14,404][WARN ][logstash.outputs.elasticsearch][main][jmeter-elasticsearch-output-stat] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"jmeter-jtl-2023.10.17", :routing=>nil}, {"isTotal"=>false, "labels"=>["%{transaction}"], "@version"=>"1", "globalLabel"=>"%{transaction}", "filename"=>"effective", "@timestamp"=>2023-10-17T09:51:13.844Z, "testname"=>"effective", "timestamp"=>"2023-10-17T09:51:13.844Z", "label"=>"%{transaction}", "tags"=>["_jsonparsefailure"], "project"=>"undefined", "origin"=>"stat"}], :response=>{"index"=>{"_index"=>"jmeter-jtl-2023.10.17", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"only write ops with an op_type of create are allowed in data streams"}}}}
[2023-10-17T09:51:14,407][WARN ][logstash.outputs.elasticsearch][main][jmeter-elasticsearch-output-stat] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"jmeter-jtl-2023.10.17", :routing=>nil}, {"isTotal"=>false, "labels"=>["%{transaction}"], "@version"=>"1", "globalLabel"=>"%{transaction}", "filename"=>"effective", "@timestamp"=>2023-10-17T09:51:13.845Z, "testname"=>"effective", "timestamp"=>"2023-10-17T09:51:13.845Z", "label"=>"%{transaction}", "tags"=>["_jsonparsefailure"], "project"=>"undefined", "origin"=>"stat"}], :response=>{"index"=>{"_index"=>"jmeter-jtl-2023.10.17", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"only write ops with an op_type of create are allowed in data streams"}}}}
[2023-10-17T09:51:14,408][WARN ][logstash.outputs.elasticsearch][main][jmeter-elasticsearch-output-stat] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"jmeter-jtl-2023.10.17", :routing=>nil}, {"isTotal"=>false, "labels"=>["%{transaction}"], "@version"=>"1", "globalLabel"=>"%{transaction}", "filename"=>"effective", "@timestamp"=>2023-10-17T09:51:13.858Z, "testname"=>"effective", "timestamp"=>"2023-10-17T09:51:13.858Z", "label"=>"%{transaction}", "tags"=>["_jsonparsefailure"], "project"=>"undefined", "origin"=>"stat"}], :response=>{"index"=>{"_index"=>"jmeter-jtl-2023.10.17", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"only write ops with an op_type of create are allowed in data streams"}}}}

```

**Comment by anasoid** [comment]
hello @johnqa 

it's preferable to keep default index name or to have index with this format jmeter-jtl-* this not related to your error.

1- for this error ([ERROR][logstash.outputs.elasticsearch][main] Failed to install template {:message=>"Got response code '403') i think it's a permission error may be the user name doesn't have enough permissions to install template.

2- for this warn WARN ][logstash.filters.json    .., it's related to parsing statistics json, stattistics.json is generated with jmeter dashboard and it look like this https://github.com/anasoid/jmeter-logstash/blob/develop/testing/file/full/in/stats-admin-20211018-082256.json, if there is any json file in input folder may it will be considered as statistics json
